#webserver
[webserver]
addr = "0.0.0.0:8080"   #监听地址
enable_ssl = false       #是否使用https 如果为true 则必须配置cert和key的路径
static_dir = "static"
debug = true

#证书设置
[webserver.certificates]
cert = "1_bestwcj.com_bundle.crt"   #证书路径
key = "2_bestwcj.com.key"           #key路径

# redis server config
[redis]
host = "129.204.180.180"
port = 6379
password = "123456"
max_idle = 5
max_active = 10

# Mysql server config
[database]
host = "129.204.180.180"
port = 3306
dbname = "vita"
username = "root"
password = "19981127"
args = "charset=utf8&parseTime=true&loc=Local"
buf_size = 10
max_idle_conns = 20
max_open_conns = 15
show_sql = true

#token设置
[token]
expires = 24     #token过期时间
secret = "JdHo15Phdg63dKjG25fElg37"

#白名单设置
[whitelist]
ip = ["10.10.*","127.0.0.1",".*"]   #白名单地址 支持golang正则表达式

#邮箱设置
[email]
host = "smtp.qq.com"
port = 465
name = "vita"
from = "1079793182@qq.com"
password = "qlykgoejralrifif"

